### ISSUE TITLE
Can't slide for brightness of a light on smartphone

### ISSUE THREAD

**Issue by thibautmery** [GladysAssistant/Gladys#1277]
First, are you sure that you found a Gladys bug?

If you are not sure, you can come discuss with us on [Gladys Community](http://community.gladysassistant.com/) 🙂

**Describe the bug**
When I am using my Iphone, it's imposible for me to slide all the slider that are in the dashboard. I have to "click" to change the value. It's not perfect even more when it's not so wide

**To Reproduce**
Using Iphone
Go to the pwa pages
Try to Slide on the slider

**Expected behavior**
Possibility to side (like the computer)

**Screenshots**

**Your Gladys installation (please complete the following information):**
Raspberry pi 4, Gladys 4.5.
IOS (updated)
Safari

**Comment by VonOx** [comment]
Maybe related to #1082 

On my side it works "sometimes" but I'didnt know what happen.

Tabler must be updated when released but maintener seems to not respond
https://github.com/tabler/tabler/issues/898

**Comment by Pierre-Gilles** [comment]
Yes this has always been the case (slider doesn't work well on touchscreen), we already have one issue referencing the bug: https://github.com/GladysAssistant/Gladys/issues/1167

No need to update Tabler (it's maybe a bit too much just to fix a slider 😅)

The only thing to do it to copy the new slider CSS class from Tabler 2 ( on https://preview.tabler.io/ ), and use this one in Gladys instead of the current class

Anyone here want to do a PR for that? :)

**Comment by Pierre-Gilles** [comment]
I found the issue !! (Took 2 hours...) 

There was a pointer-events: none by mistake in tabler CSS, I fixed it :) 

https://github.com/GladysAssistant/Gladys/pull/1284

**Comment by Pierre-Gilles** [comment]
I'm currently building a dev image (https://github.com/GladysAssistant/Gladys/actions/runs/1220591395)

I'll probably release on Monday if everything works well, in the meantime I'm interested by your feedback if you can try this image :)

**Comment by Pierre-Gilles** [comment]
Build finished!
