### ISSUE TITLE
Gladys Gateway: Sign Up link not working

### ISSUE THREAD

**Issue by LM1LC3N7** [GladysAssistant/Gladys#1369]
Hello,

I was searching for how much cost Gladys Gateway and how subscribe, but:
* On https://gateway.gladysassistant.com/login, the sign up link redirect to https://gladysassistant.com/gladys-community-package that is showing a 404 error
* On the same URL, there is no link to a page showing what is Gladys Plus and how to subscribe
* Same for https://plus.gladysassistant.com
* No link from https://gladysassistant.com to Gladys Plus (or did not notice them)

My gladys is not exposed to internet (I use a personnal VPN to connect to it). I was asking myself how to subscribe and for how much, but it seems that I need to use my Gladys first, to create an account to Gladys Plus I assume?

**Comment by Pierre-Gilles** [comment]
Hello!

Thanks for your feedback :) 

- gateway.gladysassistant.com is an old version (for v3 users) that I still keep alive for some users, but it's has not been advertised/updated anymore for the last 2 years. Where did you find "gateway.gladysassistant.com" ?

- Same for https://plus.gladysassistant.com => Indeed, that's a nice feedback! 

- No link from https://gladysassistant.com to Gladys Plus (or did not notice them) 

In the doc, there is a whole section about Gladys Plus with a link to the Gladys Plus payment page: 

<img width="417" alt="Screenshot 2021-11-22 at 15 52 23" src="https://user-images.githubusercontent.com/7365207/142882770-3e04220a-5167-4bbe-b5d4-6eec032f3aa3.png">

In the past, there was a whole "Gladys Plus" section on the website but i found out it was blocking some people to use Gladys because they thought Gladys was not free to use.

So now, the goal of the Gladys website is mostly to convert users to use Gladys (the open-source project), and then in the product itself, there are links to upgrade to Gladys Plus if they like Gladys.

> but it seems that I need to use my Gladys first, to create an account to Gladys Plus I assume?

Yes indeed that's the goal right now :)
