### ISSUE TITLE
Run Gladys without docker?

### ISSUE THREAD

**Issue by yaneony** [GladysAssistant/Gladys#1404]
I'm running debian 10/11 inside LXC and my current HomeAssistant is pretty happy without running Docker. So, the question is if it is possible to run Gladys without Docker too?

Thanks!

**Comment by LM1LC3N7** [comment]
Hello,

GladysAssistant what ment to be installed and run by non IT people, with almost no knowledge.
This is why there is some "limitations" sometimes due to the deployment architecture.

For now there are two ways to deploy Gladys:
- with the official docker image, that allows all components to work along with auto updates 
- with git clone for dev purpose, that may break some components as the zigbee compatibility which currently deploy a Zigbee2Mqtt container.

Fundamentally, the code could be updated in order to support container and "bare metal" deployment, but this would take some time, needed for other important improvements. 

Hope this help, and I let @Pierre-Gilles corrects me in case I said something wrong.

**Comment by yaneony** [comment]
Also frontend working well, where server side after cloning output too much errors (not finding modules).

**Comment by Pierre-Gilles** [comment]
Its definitely possible to run Gladys without docker (I develop on gladys every day on my machine, without docker), but it's more the "development" setup.

Indeed some integration like Zigbee2mqtt are started as docker containers next to gladys, so it's kind of mandatory to use docker for some integration :)

Why don't you use docker?

**Comment by yaneony** [comment]
1. Not a fan of
2. Running docker inside LXC container is somehow... meh :D

**Comment by Pierre-Gilles** [comment]
If you have any more questions, don't hesitate to come talk on the forum https://community.gladysassistant.com/ 🙂

We use Github mostly for bug tracking, so closing this issue as it's not really a bug!
