### ISSUE TITLE
[front] Graphs don't get resized when scale is changed while being deactivated 

### ISSUE THREAD

**Issue by gboulvin** [GladysAssistant/Gladys#1474]
**Describe the bug**
As described [Here](https://community.gladysassistant.com/t/help-probleme-avec-lagregation/6630/66?u=gboulvin), if the scale in the graph is changed while the curve is deactivated, the curves are not scaled when reactivated.

**To Reproduce and screenshots**
See [Link](https://community.gladysassistant.com/t/help-probleme-avec-lagregation/6630/66?u=gboulvin)

**Comment by gboulvin** [comment]
Still alive

**Comment by gboulvin** [comment]
Still open

Le mar. 19 juil. 2022 à 13:44, stale[bot] ***@***.***> a
écrit :

**Comment by gboulvin** [comment]
Not stale

Le sam. 17 sept. 2022 à 15:55, stale[bot] ***@***.***> a
écrit :

**Comment by Pierre-Gilles** [comment]
Writing a comment to give a bit more context. 

This is probably a bug with the lib we are using ( https://github.com/apexcharts/apexcharts.js ) 

This lib has 212 open issues currently, so it seems they have a lots of bug.. :/ 

On my side, I cannot reproduce the bug so it's very hard to test and see where the issue comes from

**Comment by gboulvin** [comment]
Not stale

**Comment by gboulvin** [comment]
Not stale

Le sam. 24 juin 2023 à 09:38, stale[bot] ***@***.***> a
écrit :

**Comment by gboulvin** [comment]
Solved in 4.26
