### ISSUE TITLE
OpenWeather API changed, needs to change API call in Gladys

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1695]
https://community.gladysassistant.com/t/openweather-meteo/7501/27?u=pierre-gilles

**Comment by baptom76** [comment]
Hello, I have just install gladys on docker. (not plus)
But the problem is here. 
In the docker logs i have this url
path: '/data/2.5/onecall?lat=YYY.YYYYYYY&lon=YY.YYYYYY&lang=fr&units=metric&cnt=1&appid=XXXXXXXXXXXXX

and not path: '/data/2.5/weather?lat=YY.YYYYYYYYYYYYYY&lon=YY.YYYYYYYY&lang=fr&units=metric&cnt=1&appid

**Comment by NicolasLemince** [comment]
PR is here: https://github.com/GladysAssistant/Gladys/pull/1734

**Comment by Pierre-Gilles** [comment]
Hello @NicolasLemince, writing a new message here, have you seen my feedbacks on the PR?

https://github.com/GladysAssistant/Gladys/pull/1734#issuecomment-1501290374

**Comment by Pierre-Gilles** [comment]
I did a PR to fix this issue : 

https://github.com/GladysAssistant/Gladys/pull/1767
