### ISSUE TITLE
DotEnv config file not loaded

### ISSUE THREAD

**Issue by Preovaleo** [GladysAssistant/Gladys#182]
Hello,

i'm just wondering :
 - why the `init.js` file doesn't load the dotenv file at all
 - why the `app.js` file only load the dotenv file when in [dev mode](https://github.com/GladysProject/Gladys/blob/master/app.js#L40)

Preovaleo

**Comment by Pierre-Gilles** [comment]
.env file is just to develop, it should not be used in production ! 

`init.js` is just useful in production ( because in dev mode, tables are automatically created at startup )

**Comment by JulienOrain** [comment]
Hello,

I just cloned and installed gladys following the README.
I still do not understand which command to launch in development mode to get my .env file loaded.
If I launch init.js, the .env file is not loaded.
If I launch app.js, the .env file is not loaded neither because the ['process.env.NODE_ENV'](https://github.com/GladysProject/Gladys/blob/6cc318af9b25a33924f905bcb8a4bd9cdfd0bf41/app.js#L35) is not setted.
I would like to know where I can set it up (ideally elsewhere than in my device parameters and obviously not in the .env file because it is only loaded in development mode).

Ideally, I would like to set the NODE_ENV var in the .env file and try to load the .env file in both production and development mode. I this feasible ? Do I miss something about that ? 

Thanks in advance and congrats for the project ;-) !
Julien

**Comment by Pierre-Gilles** [comment]
Hey ! So it's easier, I just added a command to Gladys, you can now do : 

```
npm start 
```

To start Gladys in dev mode ! 

I added this to the README of Gladys => https://github.com/GladysProject/Gladys#starting-gladys-in-development-mode

**Comment by JulienOrain** [comment]
Awesome ! I'll try soon ;-) ! Thanks !
