### ISSUE TITLE
Netatmo : no more stats after a power supply shutdown

### ISSUE THREAD

**Issue by ngeissel** [GladysAssistant/Gladys#2078]
First, are you sure that you found a Gladys bug? 

=> NOT AT ALL (i did not take time to reproduce it, but still : after reboot it is a fact : it is down)

**Describe the bug**
After a thunderstorm, power supply shut down => it should have reboot the gladys and  the netatmo station =>  no more stat => have to go to "integration=>netatmo=>reset login / password configuration ...)

**To Reproduce**

1. Simulate a thunderstorm by  Power down gladysassistant server or Netatmo 
2. Go to Netatmo device stats
3. See the lack of info (until you reset your access ...)

**Expected behavior**
A reboot of all the stuff should be crystal clear for the user with no human action  ...
 
**Screenshots**
Too bad I re set my access ... and now all is working

**Your Gladys installation (please complete the following information):**

- Raspberry Pi 3 installation  
- Manual installation: docker-compose

**Desktop (please complete the following information):**

- OS: raspbian 11
- Browser : chrome
- Version XXX

**Additional context**
N/A

**Comment by Pierre-Gilles** [comment]
@Terdious I don't know if you saw this one :)

**Comment by Terdious** [comment]
Hi @ngeissel 
I read your message (thanks @Pierre-Gilles ), I hope it doesn't have a significant impact on your use for the moment.

I started looking, I already had a similar problem (well, not really the same one). I haven't found it yet but I guess it's related to the refresh token. I am continuing the investigation. And above all I try to reproduce (because I did not succeed intentionally).
