### ISSUE TITLE
Improve node.js compatibility

### ISSUE THREAD

**Issue by Lesterpig** [GladysAssistant/Gladys#39]
According to README, only node.js v0.10 is supported right now.

> Node.js ( = v.0.10.xx, some troubles appears with node.js 0.12.x )

Gladys should work with more up-to-date versions of node.

---

If you are ok, I can check and resolve compatibility issues with the latest node.js version (v4.x) :-)

**Comment by Pierre-Gilles** [comment]
Great, no problem ! :) 

In fact Gladys is fully compatible with Node.js >= 4.xx ( because Gladys is written in pure JS ), it's only problems with dependencies written in C++ ( for example node modules handling sound in Gladys).

Somebody already tested Gladys with Node 4.xx, it was working but needed littles upgrade of some node modules, so don't hesitate to test again and propose a PR (with the correct package.json updated) :)

**Comment by Pierre-Gilles** [comment]
Gladys is now fully compatible with Node.js v4.xx ! :)
