### ISSUE TITLE
Event on device creation / deletion

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/Gladys#633]
Emit an event on device creation and/or deletion.

**Comment by Pierre-Gilles** [comment]
What's your use case for this?

**Comment by atrovato** [comment]
I am developing 3rd party services (Samsung, Google) and to notify these services of device creation / deletion, this service need to be aware of that.

**Comment by Pierre-Gilles** [comment]
Mm I see the need, but it's not as simple as that!

In the database, we have ON DELETE CASCADE triggers. Which means that if you delete a room, and in this room there are some devices, it will delete:

- Devices
- DeviceFeatures
- DeviceFeatureStates

And so on.. all that, automatically on the DB side, without any Node.js code involved.

+ I'm not a big fan of this kind of flow. Events are great for some things, but not for everything. 

We use events in Gladys when a service wants to propagate a new device state event for example.

It's great because it goes from the bottom to the top: The service is not responsible to call Gladys, because if Gladys fails, it's not the service responsibility. 

On the other hands, when something as important as this use case needs to be done, we don't want to throw an event in the water and pray for the service to do his job. It's from the top to the bottom.

Can we talk more precisely about this use-case to see what's the best we can do here? :) 

We can do a call if it's more simple for you!

**Comment by Pierre-Gilles** [comment]
Implemented in https://github.com/GladysAssistant/Gladys/pull/913
