### ISSUE TITLE
String state is not handled the same way as "number state"

### ISSUE THREAD

**Issue by Boimb** [GladysAssistant/Gladys#665]
**Is your feature request related to a problem? Please describe.**

Features "state" and "stringState" are handled with different methods. As far as I know, a "NEW_STATE" event just handled "number state" and if we want to store a new "string state" we have to deal with the deviceManager itself, which I think is not that great.

**Describe the solution you'd like**

Services should just have to emit a "NEW_STATE" event regardless if it is a "number state" or a "string state". Gladys should handle this event accordingly to the type of value the feature depends on. This should not be a services concern.

**Describe alternatives you've considered**

More a solution I've htink of :
The feature could have a new "hasStringState" property allowing gladys to store new state values the right way number/string. It would be the responsibility of the service declaring/creating the feature to set this property.

**Additional context**

If your're OK with this, I could prepare a PR implementing this, and applying this new way of handling string state to services depending on it, like camera.

Let me know you're thoughts about this.
Cheers.

**Comment by Pierre-Gilles** [comment]
Thanks for your message!

I read the code again, I agree that it's weird that the `rtsp-camera` service is not behaving the same way as other device services, it should emit an event too. 

A service should never call some Gladys code directly for an action like that, because it means the service will be responsible for error handling and it's not right. 

I'm ok with using the `DEVICE.NEW_STATE` event, but I don't think the `hasStringState` is the right way of doing this.

I think we can use the device_feature category + type to handle the data passed in the event.

**Example:** 

- "Camera" + "image" = string
- "Light" + "color" = string
- "Temperature" + "decimal" = number

I think it's really simple, because for now only camera + color are string state, the rest is numbers

What do you think of that?

**Comment by Boimb** [comment]
Yeah, I thought a flag like "has_string_state" was ugly, but my point was not to tie the code implementation and the state type.
In fine, categories and types must exist in the code, so like you suggest, that's OK to define if state is string or number from the category + type values.
I'll go this way.

**Comment by Pierre-Gilles** [comment]
Perfect ! 👍

**Comment by atrovato** [comment]
@Boimb are you still on this point ?

**Comment by Pierre-Gilles** [comment]
This issue was inactive for some time, so I'm closing it.

The goal right now is to be focused on Gladys 4 RC release and I'm putting all my effort toward this way. 

Feel free to re-open the debate in the future if you want :)
