### ISSUE TITLE
Dashboard "device in room" bug with on/off switch

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#768]
https://community.gladysassistant.com/t/dashboard-evolutions-bugs-etc/5150/4?u=pierre-gilles

"Du coup je n’ai plus accès à la commande d’extinction globale du Garage. Si j’appui sur celle-ci, le sélecteur passe à 1 puis se remet à 0.
La seule façon de le faire apparaître à 1 est de faire un refresh de la page.
Du coup idem à l’extinction pour les 3 commandes. Si j’éteins au global, la commande passe bien à 0 mais les 2 autres reste à 1 jusqu’à faire un refresh de la page. Si j’éteins l’un ou l’autre des éclairages, tout reste à 1 jusqu’au refresh manu."

**Comment by Terdious** [comment]
For information :
The bug has disappeared since yesterday without specific handling. I can't reproduce it yet. Note that I have 4 sessions of Gladys continuously. I kicked 3 sessions last night. This morning I have 4 active sessions again but the bug is not reproducible.
Also, it is important to note that when this bug was present, the command went well on the single way broker and the feedback from the Arduino as well. Neither the Arduino, the broker, nor Gladys, received any other payload.

**Comment by Pierre-Gilles** [comment]
Ok.

Closing this for now, feel free to open it again if you have the bug.
