### ISSUE TITLE
Gladys is not showing error in front when restore is corrupted

### ISSUE THREAD

**Issue by ErwannLegeay** [GladysAssistant/Gladys#859]
I have a bad backup of my Gladys instance.
I just tried to restore it to see what happens.
When i go to the backup screen while being signed in, I try to restore the corrupted backup and I obtain indefinely this screen

<img width="1247" alt="Capture d’écran 2020-08-26 à 16 38 43" src="https://user-images.githubusercontent.com/5676655/91318096-28585680-e7bb-11ea-8667-94bc32cd22a9.png">

In the Logs this is what I can see : 

<img width="534" alt="Capture d’écran 2020-08-26 à 16 39 30" src="https://user-images.githubusercontent.com/5676655/91318139-33ab8200-e7bb-11ea-853a-abc7a2918c54.png">

**Comment by Pierre-Gilles** [comment]
Hey @ErwannLegeay, 

I don't remember if we talked about that somewhere else (I think so because this bug is fixed)

I'm closing this issue, but feel free to contact me on my email, on the forum, or reopen the issue here if the bug is still present.

Sorry if I didn't reply, the Github repo was quite bloated that's why we just install a stale-bot to help us!!

**Comment by ErwannLegeay** [comment]
Hey @Pierre-Gilles we talked about it for sure (maybe on slack ?) and at this time I had no choice but to restart from 0 (I had not so much things that was setted on my Gladys instance so it was not a big problem). I don't have any trouble anymore so I haven't try to restore a new backup to test if it was OK. So no worries about the closing of this issue because it's now OK for me :)
