### ISSUE TITLE
MQTT Bug: Adding a module with the same external_id delete another one

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#935]
"MQTT: j'ai tenté de supprimer, ajouter un module avec un nom plus simple, et ça m'a supprimé la sonde mqtt extérieure :("

"je pense avoir un bug... avec mqtt, je cree avec NOUVEAU, ça marche. Si j'ajoute, le 1er créé est remplacé par le 2nd :))))"

**Comment by Pierre-Gilles** [comment]
@atrovato Interesting bug:

https://streamable.com/95cp5k

Do you have an idea how we could fix it? Because server-side, the create device is a "create or update"... 

Maybe in the MQTT case, we should do a query client-side for new device to test if they exist before. 

What do you think?

**Comment by atrovato** [comment]
To keep same order, we can sort by device id. This should not be overriden on update, no?

**Comment by Pierre-Gilles** [comment]
Same order? I don't understand.

**Comment by atrovato** [comment]
Ok sorry, I was not really in.
I read again, and I understand what you mean.

So maybe, in `device.create.js` file, when we "first verify that device doesn't already exist", we get the device by id and external_id?
Or we enter in update case only if incoming device has an id?

But if this changes, we have to check all integrations for any regression.
I'm not fan to do something specific in client-side, because it's going to be the "normal way" do this, and call GET before POST is not a good practice.

**Comment by Pierre-Gilles** [comment]
> So maybe, in device.create.js file, when we "first verify that device doesn't already exist", we get the device by id and external_id? Or we enter in update case only if incoming device has an id ?

I think what we can do is: 

- if the incoming device has an id, update the device
- else, try to create it (will reject with a 409 ALREADY EXIST if external_id is already there)

But it seems a little bit too easy to be true, do you remember why we did that? (create or update on exist of external_id only?) I think there was a real reason for one integration or for one future integration, but I can't remember why!

> I'm not fan to do something specific in client-side

Not a big fan either

**Comment by Pierre-Gilles** [comment]
This bug still exists.

**Comment by atrovato** [comment]
Not stale.

**Comment by Pierre-Gilles** [comment]
Not stale
